
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[210] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   84,   82,
       80,   32,   68,   73,   58,   82,   22,   23,   56,   54,
       20,   55,   82,   57,   69,   70,   21,   60,   59,   64,
       53,   53,   24,   25,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   26,   82,   27,   82,
       10,   28,   12,    9,   12,   79,   81,   74,   79,   29,
       82,   82,   30,   82,   31,   82,   11,    8,   11,    7,
       62,   66,    0,    2,    1,    0,    0,    0,   70,   61,
       65,   63,   53,    0,   53,   53,   53,   53,   34,   53,

       53,   53,   53,   35,   53,   53,   53,   53,   53,   53,
       53,   67,    0,    6,   75,   78,   77,   76,    0,    0,
        0,    0,    0,   18,    4,    3,    5,   71,   72,   53,
       53,   53,   53,   53,   53,   53,   39,   40,   53,   53,
       53,   53,   53,   53,   53,    0,    0,    0,    0,    0,
       19,   45,   53,   53,   53,   53,   36,   53,   53,   53,
       43,   53,   53,   37,   46,   53,    0,    0,    0,    0,
        0,   53,   51,   42,   53,   53,   38,   47,   41,   53,
       53,   33,    0,    0,    0,    0,    0,   53,   53,   48,
       52,   49,    0,    0,    0,    0,   15,   44,   53,    0,

       14,    0,   17,   50,   13,    0,    0,   16,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       25,   26,   27,    1,    1,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   23,   37,   38,   39,   40,
       41,   42,   23,   43,   44,   45,   46,   47,   48,   23,
       49,   23,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[53] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    1,    1,
        1,    1,    2,    2,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[216] =
    {   0,
        0,  264,  266,  265,   50,   51,   52,   53,   56,   60,
       57,   61,   64,   65,   62,   63,  264,  263,  265,  271,
      271,  271,  243,  271,  271,  255,  271,  271,  271,  271,
      271,  271,   52,   60,   67,   71,  271,  241,  240,  239,
        0,   94,  271,  271,   34,  218,  217,  101,   55,   54,
      214,  224,  210,  211,  212,  217,  271,  200,  271,  208,
      271,  271,  271,  271,  233,  271,  271,  271,  102,  271,
       75,  207,  271,   57,  271,   98,  271,  271,  231,  271,
      271,  271,  105,  271,  271,  108,  116,  118,  126,  271,
      271,  271,    0,  128,  134,  205,  213,  204,  197,  198,

      203,  199,  196,    0,  193,  201,   82,  193,  189,  198,
      197,  271,  189,  271,  271,  271,  271,  271,  185,  202,
      190,  191,  194,  271,  271,  271,  271,  136,  138,  188,
      197,  117,  195,  191,  178,  193,    0,    0,  180,  188,
      172,  181,  184,  184,  176,  185,  169,  166,  181,  177,
      271,  176,  170,  161,  169,  166,    0,  171,  157,  156,
        0,  157,  159,    0,    0,  166,  163,  166,  159,  153,
      153,  164,    0,    0,  151,  158,    0,    0,    0,  149,
      154,    0,  148,  154,  141,  146,  181,  142,  135,    0,
        0,    0,  152,  177,  122,  164,  163,    0,  132,  161,

      157,  121,  147,    0,  136,   91,  115,   90,  271,  168,
      170,  172,  174,  176,   70
    } ;

static yyconst flex_int16_t yy_def[216] =
    {   0,
      209,    1,  210,  210,  211,  211,  212,  212,  213,  213,
      213,  213,  213,  213,  214,  214,  213,  213,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      215,  215,  209,  209,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  215,  209,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  209,  209,  209,  209,  209,
      209,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  209,  209,  209,  209,
      209,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  209,  209,  209,  209,  209,  215,  215,  215,
      215,  215,  209,  209,  209,  209,  209,  215,  215,  209,

      209,  209,  209,  215,  209,  209,  209,  209,    0,  209,
      209,  209,  209,  209,  209
    } ;

static yyconst flex_int16_t yy_nxt[324] =
    {   0,
       20,   21,   22,   23,   24,   20,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   20,   44,   41,   45,   46,
       47,   48,   49,   41,   41,   50,   41,   41,   41,   41,
       41,   51,   52,   53,   54,   41,   55,   56,   41,   57,
       58,   59,   64,   64,   67,   67,   68,   68,   70,   73,
       65,   65,   70,   73,   78,   78,   75,   75,   83,   83,
       84,   93,   79,   79,   96,   85,   97,   69,   69,   76,
       76,   86,  101,   87,   87,   86,  104,   89,   89,  123,
       88,  208,  102,  105,   88,  103,  124,   74,   88,   71,

       72,   74,   88,   71,   72,   94,  115,   94,  125,  140,
       95,   95,   94,  126,   94,  119,  208,   95,   95,  120,
      207,   83,   83,  121,  128,  128,  141,  116,   88,   94,
       86,   94,   87,   87,  129,  129,   88,  205,  100,   88,
       86,  117,   89,   89,  129,  129,  118,   88,  203,   88,
       95,   95,  128,  128,  129,  129,  206,   88,  201,   88,
      154,  155,  205,  204,  197,  203,  202,   88,   61,   61,
       63,   63,   66,   66,   20,   20,   77,   77,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  127,  122,  114,  113,
      112,  111,  110,  109,  108,  107,  106,   99,   98,   92,
       91,   90,   82,   81,  209,   80,   80,   62,   62,   60,
       19,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,

      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209
    } ;

static yyconst flex_int16_t yy_chk[324] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    6,    7,    8,    7,    8,    9,   11,
        5,    6,   10,   12,   15,   16,   13,   14,   33,   33,
       34,  215,   15,   16,   45,   34,   45,    7,    8,   13,
       14,   35,   49,   35,   35,   36,   50,   36,   36,   74,
       35,  208,   49,   50,   36,   49,   74,   11,   35,    9,

        9,   12,   36,   10,   10,   42,   69,   42,   76,  107,
       42,   42,   48,   76,   48,   71,  207,   48,   48,   71,
      206,   83,   83,   71,   86,   86,  107,   69,   83,   88,
       87,   88,   87,   87,   88,   88,   83,  205,   48,   87,
       89,   69,   89,   89,   94,   94,   69,   87,  203,   89,
       95,   95,  128,  128,  129,  129,  202,   89,  201,  128,
      132,  132,  200,  199,  197,  196,  195,  128,  210,  210,
      211,  211,  212,  212,  213,  213,  214,  214,  194,  193,
      189,  188,  187,  186,  185,  184,  183,  181,  180,  176,
      175,  172,  171,  170,  169,  168,  167,  166,  163,  162,

      160,  159,  158,  156,  155,  154,  153,  152,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      136,  135,  134,  133,  131,  130,  123,  122,  121,  120,
      119,  113,  111,  110,  109,  108,  106,  105,  103,  102,
      101,  100,   99,   98,   97,   96,   79,   72,   65,   60,
       58,   56,   55,   54,   53,   52,   51,   47,   46,   40,
       39,   38,   26,   23,   19,   18,   17,    4,    3,    2,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,

      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
#define LIST                { strncat(buf, yytext, sizeof(buf) - strlen(buf) - 1); }
#define SADD(s)                { strncat(strbuf, s, sizeof(strbuf) - strlen(strbuf) - 1); }
#define SRADD(s)                { strncat(strRealBuf, s, sizeof(strRealBuf) - strlen(strRealBuf) - 1); }
#define token(t)            { LIST; if (Opt_Token) printf("<%s>\n", #t); }
#define tokenString(t, s)   { LIST; if (Opt_Token) printf("<%s:%s>\n", t, s); }
#define tokenStringN(t, s)   {if (Opt_Token) printf("<%s:%s>\n", t, s); }
#define MAX_LINE_LENGTH 257
#define MAX_ID_LENGTH 257
#define MAX_ID_COUNT 1024
#include "symtbl.h"
#include "string.h"
#include "y.tab.h"



char* strdup(const char*);
int Opt_Source = 0;
int Opt_Token = 0;
int Opt_Statistic = 0;
int Opt_Symbol = 0;
int linenum = 1;
int* ctrl_target = NULL;
char buf[MAX_LINE_LENGTH];
char strbuf[MAX_LINE_LENGTH];
char strRealBuf[MAX_LINE_LENGTH];
void line_process(void);
void register_id(const char* );
void dispose_id_table();
extern void add_string(char*);
extern FILE* asmOut;

#line 626 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define SPAN_COMMENT 2
#define STRING_STATE 3
#define PRAGMA_TYPE 4
#define PRAGMA_OP 5
#define PRAGMA_COMMENT 6
#define PRAGMA_SPAN_COMMENT 7
#define NEW_LINE_NOW 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 38 "scanner.l"


 /**** One line comment ****/
#line 850 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 210 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 271 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "scanner.l"
{
   LIST;
   BEGIN COMMENT;
}
	YY_BREAK
/**** Multiple line comment ****/
case 2:
YY_RULE_SETUP
#line 46 "scanner.l"
{
   LIST;
   BEGIN SPAN_COMMENT;
}
	YY_BREAK
/**** One line comment ****/
case 3:
YY_RULE_SETUP
#line 51 "scanner.l"
{
   LIST;
   BEGIN COMMENT;
}
	YY_BREAK
/**** Multiple line comment ****/
case 4:
YY_RULE_SETUP
#line 56 "scanner.l"
{
   LIST;
   BEGIN PRAGMA_SPAN_COMMENT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "scanner.l"
{
   LIST;
   BEGIN NEW_LINE_NOW;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "scanner.l"
{
   LIST;
   BEGIN INITIAL;
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
#line 70 "scanner.l"
case 8:
/* rule 8 can match eol */
#line 71 "scanner.l"
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 71 "scanner.l"
{
   LIST;
   line_process();
}
	YY_BREAK
/**** Eat all character when COMMENT or SPAN_COMMENT ****/
case 10:
YY_RULE_SETUP
#line 76 "scanner.l"
{
    LIST;
}
	YY_BREAK
case 11:
#line 80 "scanner.l"
case 12:
YY_RULE_SETUP
#line 80 "scanner.l"
{
    LIST;
}
	YY_BREAK
/**** Pragma Directives ****/
/* Enter pragma mode , try to find type */
case 13:
YY_RULE_SETUP
#line 86 "scanner.l"
{
    LIST;
    BEGIN PRAGMA_TYPE;
}
	YY_BREAK
/* Filter the type */
case 14:
YY_RULE_SETUP
#line 91 "scanner.l"
{
    LIST;
    ctrl_target = &Opt_Source;    
    BEGIN PRAGMA_OP;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 96 "scanner.l"
{
    LIST;
    ctrl_target = &Opt_Token;    
    BEGIN PRAGMA_OP;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "scanner.l"
{
    LIST;
    ctrl_target = &Opt_Statistic;    
    BEGIN PRAGMA_OP;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "scanner.l"
{
    LIST;
    ctrl_target = &Opt_Symbol;    
    BEGIN PRAGMA_OP;
}
	YY_BREAK
/* Filter option */
case 18:
YY_RULE_SETUP
#line 113 "scanner.l"
{
    LIST;
    *ctrl_target = 1;
    BEGIN PRAGMA_COMMENT;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 118 "scanner.l"
{
    LIST;
    *ctrl_target = 0;
    BEGIN PRAGMA_COMMENT;
}
	YY_BREAK
/**** delimoters ****/
case 20:
YY_RULE_SETUP
#line 129 "scanner.l"
{
    tokenString("delim", ","); 
    return COMMA;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 133 "scanner.l"
{
    tokenString("delim", ";"); 
    return SEMICOLON;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 137 "scanner.l"
{
    tokenString("delim", "("); 
    return '(';
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 141 "scanner.l"
{
    tokenString("delim", ")"); 
    return ')';
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 145 "scanner.l"
{
    tokenString("delim", "["); 
    return '[';
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 149 "scanner.l"
{
    tokenString("delim", "]"); 
    return ']';

}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 154 "scanner.l"
{
    tokenString("delim", "{"); 
    return '{';
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 158 "scanner.l"
{
    tokenString("delim", "}"); 
    return '}';
}
	YY_BREAK
/**** new line ****/
case 28:
/* rule 28 can match eol */
#line 169 "scanner.l"
case 29:
/* rule 29 can match eol */
#line 170 "scanner.l"
case 30:
/* rule 30 can match eol */
#line 171 "scanner.l"
case 31:
/* rule 31 can match eol */
#line 172 "scanner.l"
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 172 "scanner.l"
{
    BEGIN INITIAL;
    LIST;
    line_process();
}
	YY_BREAK
/**** keyword ****/
case 33:
YY_RULE_SETUP
#line 179 "scanner.l"
{
    tokenString("KW", "while"); 
    return KW_WHILE;   
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 183 "scanner.l"
{
    tokenString("KW", "do"); 
    return KW_DO;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 187 "scanner.l"
{
    tokenString("KW", "if"); 
    return KW_IF;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 191 "scanner.l"
{
    tokenString("KW", "else"); 
    return KW_ELSE;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 195 "scanner.l"
{
    tokenString("KW", "true"); 
    yylval.typeStruct.v_type = T_BOOL;
    yylval.typeStruct.is_const = 1;
    yylval.typeStruct.dim = 0;
    yylval.typeStruct.val = 1;
    return BOOLEAN_CONSTANT;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 203 "scanner.l"
{
    tokenString("KW", "false"); 
    yylval.typeStruct.v_type = T_BOOL;
    yylval.typeStruct.is_const = 1;
    yylval.typeStruct.dim = 0;
    yylval.typeStruct.val = 0;
    return BOOLEAN_CONSTANT;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 211 "scanner.l"
{
    tokenString("KW", "for"); 
    return KW_FOR;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 215 "scanner.l"
{
    tokenString("KW", "int");
    yylval.value = T_INT;
    return INT;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 220 "scanner.l"
{
    tokenString("KW", "print"); 
    return KW_PRINT;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 224 "scanner.l"
{
    tokenString("KW", "const"); 
    return CONST;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 228 "scanner.l"
{
    tokenString("KW", "read"); 
    return KW_READ;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 232 "scanner.l"
{
    tokenString("KW", "boolean"); 
    yylval.value = T_BOOL;
    return BOOL;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 237 "scanner.l"
{
    tokenString("KW", "bool"); 
    yylval.value = T_BOOL;
    return BOOL;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 242 "scanner.l"
{
    tokenString("KW", "void"); 
    yylval.value = T_VOID;
    return VOID;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 247 "scanner.l"
{
    tokenString("KW", "float"); 
    yylval.value = T_FLOAT;
    return FLOAT;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 252 "scanner.l"
{
    tokenString("KW", "double"); 
    yylval.value = T_DOUBLE;
    return DOUBLE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 257 "scanner.l"
{
    tokenString("KW", "string"); 
    yylval.value = T_STRING;
    return STRING;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 262 "scanner.l"
{
    tokenString("KW", "continue"); 
    return KW_CONTINUE;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 266 "scanner.l"
{
    tokenString("KW", "break"); 
    return KW_BREAK;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 270 "scanner.l"
{
    tokenString("KW", "return"); 
    return KW_RETURN;
}
	YY_BREAK
/**** Identifier ****/
case 53:
YY_RULE_SETUP
#line 277 "scanner.l"
{
    tokenString("id", yytext);
    // copy name
    yylval.text = (char *)strdup(yytext);
    add_string(yylval.text);
    //register_id(yytext);
    return ID;
}
	YY_BREAK
/**** Operator ****/
case 54:
YY_RULE_SETUP
#line 288 "scanner.l"
{
    token("+");
    return '+';
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 292 "scanner.l"
{
    token("-");
    return '-';
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 296 "scanner.l"
{
    token("*");
    return '*';
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 300 "scanner.l"
{
    token("/");
    return '/';
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 304 "scanner.l"
{
    token("%");
    return '%';
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 308 "scanner.l"
{
    token("=");
    return ASSIGN;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 312 "scanner.l"
{
    token("<");
    yylval.value = OP_LT;
    return L_OP_LT;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 317 "scanner.l"
{
    token("<=");
    yylval.value = OP_LE;
    return L_OP_LE;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 322 "scanner.l"
{
    token("!=");
    yylval.value = OP_NE;
    return L_OP_NE;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 327 "scanner.l"
{
    token(">=");
    yylval.value = OP_GE;
    return L_OP_GE;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 332 "scanner.l"
{
    token(">");
    yylval.value = OP_GT;
    return L_OP_GT;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 337 "scanner.l"
{
    token("==");
    yylval.value = OP_EQ;
    return L_OP_EQ;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 342 "scanner.l"
{
    token("&&");
    yylval.value = OP_AND;
    return L_OP_AND;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 347 "scanner.l"
{
    token("||");
    yylval.value = OP_OR;
    return L_OP_OR;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 352 "scanner.l"
{
    token("!");
    yylval.value = OP_NOT;
    return L_OP_NOT;
}
	YY_BREAK
/**** Interger Constant ****/
case 69:
#line 360 "scanner.l"
case 70:
YY_RULE_SETUP
#line 360 "scanner.l"
{
    tokenString("integer", yytext);
    yylval.typeStruct.v_type = T_INT;
    yylval.typeStruct.is_const = 1;
    yylval.typeStruct.val = atoi(yytext);
    yylval.typeStruct.dim = 0;
    return INTEGER_CONSTANT;
}
	YY_BREAK
/**** Floating-Point Constant ****/
case 71:
YY_RULE_SETUP
#line 370 "scanner.l"
{
    tokenString("float", yytext);
    yylval.typeStruct.v_type = T_FLOAT;
    yylval.typeStruct.is_const = 1;
    yylval.typeStruct.dim = 0;
    yylval.typeStruct.is_raw = true;
    yylval.typeStruct.fval = atof(yytext);
    return FLOATING_CONSTANT;
}
	YY_BREAK
/**** Scientic Notations ****/
case 72:
YY_RULE_SETUP
#line 381 "scanner.l"
{ 
    tokenString("scientific", yytext);
    yylval.typeStruct.v_type = T_DOUBLE;
    yylval.typeStruct.is_const = 1;
    yylval.typeStruct.dim = 0;
    yylval.typeStruct.is_raw = true;
    yylval.typeStruct.dval = atof(yytext);
    return FLOATING_CONSTANT;
}
	YY_BREAK
/*** String Constant ***/
/* Enter String Mode */
case 73:
YY_RULE_SETUP
#line 394 "scanner.l"
{
    LIST;
    strbuf[0] = '\0';
    strRealBuf[0] = '\0';
    BEGIN STRING_STATE;
}
	YY_BREAK
/* End of String */
case 74:
YY_RULE_SETUP
#line 401 "scanner.l"
{
    LIST;   
    tokenStringN("string", strbuf);
    BEGIN INITIAL;
    yylval.typeStruct.v_type = T_STRING;
    yylval.typeStruct.is_const = 1;
    yylval.typeStruct.dim = 0;
    yylval.typeStruct.sval = (char *)strdup(strRealBuf);
    add_string(yylval.typeStruct.sval);
    strbuf[0] = '\0';
    strRealBuf[0] = '\0';
    return STRING_CONSTANT;
}
	YY_BREAK
/* escape:" */
case 75:
YY_RULE_SETUP
#line 415 "scanner.l"
{
    LIST;
    SADD("\"");
    SRADD("\"");
}
	YY_BREAK
/* escape:\t */
case 76:
YY_RULE_SETUP
#line 421 "scanner.l"
{
    LIST;
    SADD("\t");
    SRADD("\\t");
}
	YY_BREAK
/* escape:\n */
case 77:
YY_RULE_SETUP
#line 427 "scanner.l"
{
    LIST;
    SADD("\n");
    SRADD("\\n");
}
	YY_BREAK
/* escape:\ */
case 78:
YY_RULE_SETUP
#line 433 "scanner.l"
{
    LIST;
    SADD("\\");
    SRADD("\\\\");
}
	YY_BREAK
/* Rest of character in string */
case 79:
YY_RULE_SETUP
#line 439 "scanner.l"
{
    LIST;
    SADD(yytext);
    SRADD(yytext);
}
	YY_BREAK
/* Whitespace */
case 80:
YY_RULE_SETUP
#line 447 "scanner.l"
{
    LIST;
}
	YY_BREAK
case 81:
/* rule 81 can match eol */
#line 452 "scanner.l"
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 452 "scanner.l"
{ // Unrecognized character
    fprintf(ERR_FD, "Error at line %d: %s\n", linenum, yytext);
    dispose_id_table();
    exit(1);
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 460 "scanner.l"
ECHO;
	YY_BREAK
#line 1614 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(SPAN_COMMENT):
case YY_STATE_EOF(STRING_STATE):
case YY_STATE_EOF(PRAGMA_TYPE):
case YY_STATE_EOF(PRAGMA_OP):
case YY_STATE_EOF(PRAGMA_COMMENT):
case YY_STATE_EOF(PRAGMA_SPAN_COMMENT):
case YY_STATE_EOF(NEW_LINE_NOW):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 210 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 210 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 209);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 460 "scanner.l"



/* Declare ID-table related structs */

struct TableEntry{
    const char* id;
    int count;
};

typedef struct TableEntry ENTRY;

/* ID pool , for saving space */
char** id_pool = NULL;
int id_count = 0; // how many IDs in the pool

/* ID table , for sorting */
ENTRY* id_table  = NULL;
int table_count = 0;


/* new line process */
void line_process(void){
    if (Opt_Source){
        printf("%d:%s\n", linenum, buf);
    }
#ifdef SOURCE_IN_ASSEMBLY
    fprintf(asmOut,"; Line #%d: %s\n", linenum, buf);
#endif
    ++linenum;
    buf[0] = '\0';
}

/* Add new id entry in pool */
/* when full, return NULL */
char* add_new_id(const char* new_id){
    char* ptr = NULL;
    if(id_count < MAX_ID_COUNT){
        // if there is a space
        strncpy(id_pool[id_count],new_id,MAX_ID_LENGTH);
        ptr = id_pool[id_count++];
    }
    return ptr;
}


/* register a new id */
void register_id(const char* new_id){
    const char* id_ptr = NULL;
    int count = -1;
    // search in table
    int i=0;
    for(i=0;i<table_count;i++){
        if(strncmp(new_id,id_table[i].id,MAX_ID_LENGTH)==0){
            // find in table
            id_ptr = id_table[i].id;
            // increase counter
            count = id_table[i].count += 1;
            break;
        }
    }
    if(!id_ptr){ // Not found in table
        // Add new id to pool
        id_ptr = add_new_id(new_id);
        if(id_ptr){
            // when success
            id_table[table_count].id = id_ptr;
            count = id_table[table_count].count = 1;
            ++table_count;
        }
    }
    // debug output
    //printf("new id %s , count %d , at %p\n",new_id,count,id_ptr);
    

}

/* allocate id pool */
void init_id_pool(){
    id_count = 0;
    id_pool = (char**)malloc(sizeof(char*)*MAX_ID_COUNT);
    int i;
    for(i=0;i<MAX_ID_COUNT;i++){
        id_pool[i] = (char*)malloc(sizeof(char)*MAX_ID_LENGTH);
    }
}

/* release id pool */
void dispose_id_pool(){
    int i;
    for(i=0;i<MAX_ID_COUNT;i++){
        free(id_pool[i]);
    }
    free(id_pool);
}

/* init id table , include id pool */
void init_id_table(){
    // Init the pool first
    init_id_pool();    
    // create the table
    id_table = (ENTRY*)malloc(sizeof(ENTRY)*MAX_ID_COUNT);

    
}
/* release id table , include id pool */
void dispose_id_table(){
    
    // free the table
    free(id_table);
    // finally, dispose the pool
    dispose_id_pool();  
}

// compare function
int table_cmp(const void* va,const void* vb){
    const ENTRY* a = (const ENTRY*)va;
    const ENTRY* b = (const ENTRY*)vb;
    return a->count - b->count;
}

// Sort the id table with qsort
void sort_id_table(){
    qsort(id_table,table_count,sizeof(ENTRY),table_cmp);    
}

void show_freq_table(){
    // sort the table
    sort_id_table();
    // print the table
    printf("frequencies of identifiers:\n");
    int i;
    for(i=0;i<table_count;i++){
        printf("%s\t%d\n",id_table[i].id,id_table[i].count);
    }
}


/*
int main( int argc, char **argv )
{
    if (argc >= 2)
    {
        yyin = fopen( argv[1], "r" );
        if ( NULL == yyin ) {
            fprintf( ERR_FD, "Cannot open: %s\n", argv[1] );
            exit(-1);
        }
    }
    else
    {
        yyin = stdin;
    }

    init_id_table();

    buf[0] = '\0';
    yylex();

    if (Opt_Statistic)
    {
        show_freq_table();
        // Print frequency table
    }
    dispose_id_table();

    exit(0);
}
*/


