
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[615] =
    {   0,
        0,    0,    0,    0,   67,   67,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       82,   80,   77,   78,   23,   80,   13,   80,    1,    2,
       11,    9,    3,   10,   12,   74,   74,    4,   15,   14,
       19,   73,    5,   73,    6,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,    7,   80,    8,
       71,   70,   23,   71,   13,   71,    1,    2,   11,    9,
        3,   10,   12,    4,   15,   14,   19,    5,   71,    6,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,    7,   71,    8,   67,   68,   23,   67,   13,

       67,    1,    2,   11,    9,    3,   10,   12,    4,   15,
       14,   19,    5,   67,    6,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,    7,   67,    8,
       49,   48,   23,   49,   13,   49,    1,    2,   11,    9,
        3,   10,   12,    4,   15,   14,   19,    5,   49,    6,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,    7,   49,    8,   53,   52,   23,   53,   13,
       53,    1,    2,   11,    9,    3,   10,   12,    4,   15,
       14,   19,    5,   53,    6,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,    7,   53,

        8,   64,   65,   23,   64,   13,   64,    1,    2,   11,
        9,    3,   10,   12,    4,   15,   14,   19,    5,   64,
        6,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,    7,   64,    8,   12,    5,   79,    6,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   57,   56,   23,   57,   13,   57,    1,    2,
       11,    9,    3,   10,   12,    4,   15,   14,   19,    5,
       57,    6,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,    7,   57,    8,   61,   60,
       23,   61,   13,   61,    1,    2,   11,    9,    3,   10,

       12,    4,   15,   14,   19,    5,   61,    6,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,    7,   61,    8,   77,   17,    0,   21,   72,   66,
        0,    0,    0,   76,   74,   74,   16,   20,   18,   73,
       73,   73,   73,   25,   73,   73,   73,   73,   26,   73,
       73,   73,   73,   73,   73,   73,   22,   69,    0,    0,
        0,   25,    0,    0,    0,    0,   26,    0,    0,    0,
        0,    0,    0,    0,   67,   17,   67,   21,   66,   16,
       20,   18,   67,   67,   67,   25,   67,   67,   67,   67,
       26,   67,   67,   67,   67,   67,   67,   67,   22,    0,

        0,    0,    0,   50,   62,   63,    0,   54,    0,   58,
        0,   75,    0,    0,    0,   76,   76,   73,   73,   73,
       73,   73,   73,   73,   30,   31,   73,   73,   73,   73,
       73,   73,   73,    0,    0,    0,    0,    0,    0,    0,
       30,   31,    0,    0,    0,    0,    0,    0,    0,   67,
       67,   67,   67,   67,   67,   67,   67,   30,   31,   67,
       67,   67,   67,   67,   67,   67,    0,    0,    0,   51,
       50,   55,   54,   59,   58,    0,   75,   75,    0,   36,
       73,   73,   73,   73,   27,   73,   73,   73,   34,   73,
       73,   28,   37,   73,   36,    0,    0,    0,    0,   27,

        0,    0,    0,   34,    0,    0,   28,   37,    0,   67,
       36,   67,   67,   67,   67,   27,   67,   67,   67,   34,
       67,   67,   28,   37,   67,    0,    0,    0,   51,   55,
       59,    0,   75,   75,    0,    0,   73,   42,   33,   73,
       73,   29,   38,   32,   73,   73,   24,    0,   42,   33,
        0,    0,   29,   38,   32,    0,    0,   24,   67,   67,
       42,   33,   67,   67,   29,   38,   32,   67,   67,   24,
        0,    0,   46,    0,    0,    0,   73,   73,   39,   43,
       40,    0,    0,   39,   43,   40,   67,   67,   67,   39,
       43,   40,   45,    0,   46,   44,   35,   73,   35,    0,

       44,   35,   67,   45,    0,   44,   41,   41,   44,   41,
        0,   47,   47,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   23,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       24,   25,   26,   22,   22,   22,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   22,   36,   37,   38,   39,
       40,   41,   22,   42,   43,   44,   45,   46,   47,   22,
       22,   22,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[51] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[617] =
    {   0,
        0,    0,   50,    0,  100,    0,  150,    0,  200,    0,
      250,    0,  300,    0,    0,    0,  350,    0,  400,    0,
      976,  977,  973,  977,  954,  932,  977,  965,  977,  977,
      977,  977,  977,  977,  441,  438,  443,  977,  951,  950,
      949,    0,    0,    0,    0,  422,  928,  927,  929,  431,
      431,  923,  933,  919,  920,  921,  926,  977,  910,  977,
      977,  977,  938,  916,  977,  949,  977,  977,  940,  977,
      977,  977,  939,  977,  933,  932,  931,  977,  977,  977,
      425,  910,  909,  911,  445,  441,  905,  915,  901,  902,
      903,  908,  977,  892,  977,    0,  977,  920,  898,    0,

      931,    0,    0,    0,    0,    0,    0,  922,    0,  916,
      915,  914,    0,    0,    0,  435,  893,  892,  894,  449,
      449,  888,  898,  884,  885,  886,  891,    0,  875,    0,
      977,  977,  903,  881,  977,  914,  977,  977,  977,  977,
      977,  977,  905,  977,  899,  898,  897,  977,  977,  977,
      450,  876,  875,  877,  456,  452,  871,  881,  454,  455,
      871,  876,  977,  860,  977,  977,  977,  888,  866,  977,
      899,  977,  977,  977,  977,  977,  977,  890,  977,  884,
      883,  882,  977,  977,  977,  459,  861,  860,  862,  473,
      470,  472,  856,  866,  852,  853,  854,  859,  977,  843,

      977,  977,  977,  871,  849,  977,  882,  977,  977,  977,
      977,  977,  977,  493,  977,  868,  867,  866,  977,  977,
      977,  465,  845,  844,  846,  479,  482,  840,  850,  836,
      837,  838,  843,  977,  827,  977,  860,  977,  977,  977,
      475,  834,  833,  835,  485,  488,  829,  839,  825,  826,
      827,  832,  977,  977,  845,  823,  977,  856,  977,  977,
      977,  977,  977,  977,  847,  977,  841,  840,  839,  977,
      977,  977,  484,  818,  817,  819,  491,  491,  497,  813,
      823,  809,  810,  811,  816,  977,  800,  977,  977,  977,
      828,  806,  977,  839,  977,  977,  977,  977,  977,  977,

      830,  977,  824,  823,  822,  977,  977,  977,  492,  801,
      800,  802,  506,  503,  505,  796,  806,  792,  793,  794,
      799,  977,  783,  977,  829,  977,  788,  977,  977,  977,
      462,  524,  534,  543,  547,  552,  977,  977,  977,    0,
      789,  797,  788,  781,  782,  787,  783,  780,    0,  777,
      785,  518,  777,  773,  782,  781,  977,  977,  775,  783,
      774,  767,  768,  773,  769,  766,  977,  763,  771,  540,
      763,  759,  768,  767,    0,    0,  759,    0,    0,    0,
        0,    0,  760,  768,  759,  752,  753,  758,  754,  751,
        0,  748,  756,  544,  748,  744,  753,  752,    0,  741,

      531,  749,  752,  781,  977,  977,  750,  779,  748,  777,
      751,  563,  536,  573,  583,  560,  565,  740,  749,  548,
      747,  743,  730,  745,    0,    0,  732,  740,  724,  733,
      736,  736,  728,  727,  736,  558,  734,  730,  717,  732,
      977,  977,  719,  727,  711,  720,  723,  723,  715,  724,
      713,  722,  564,  720,  716,  703,  718,    0,    0,  705,
      713,  697,  706,  709,  709,  701,  695,  692,  704,  732,
      731,  730,  729,  728,  727,  695,  595,  599,  604,  696,
      690,  681,  689,  686,    0,  691,  677,  676,    0,  677,
      679,    0,    0,  686,  685,  679,  670,  678,  675,  977,

      680,  666,  665,  977,  666,  668,  977,  977,  675,  672,
      673,  667,  658,  666,  663,    0,  668,  654,  653,    0,
      654,  656,    0,    0,  663,  664,  657,  652,  688,  687,
      686,  649,  615,  620,  625,  636,  659,    0,    0,  646,
      653,    0,    0,    0,  644,  649,    0,  654,  977,  977,
      640,  645,  977,  977,  977,  636,  641,  977,  635,  644,
        0,    0,  631,  637,    0,    0,    0,  627,  632,    0,
      630,  611,  647,  620,  641,  646,  606,  599,    0,    0,
        0,  601,  588,  977,  977,  977,  601,  586,  579,    0,
        0,    0,  621,  575,  615,  608,    0,  574,  977,  572,

      596,    0,  564,  591,  550,  572,    0,  977,  570,    0,
      520,  537,  485,  977,  450,  677
    } ;

static yyconst flex_int16_t yy_def[617] =
    {   0,
      614,    1,  614,    3,  614,    5,  614,    7,  614,    9,
      614,   11,  614,   13,   13,   13,  614,   17,  614,   19,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  615,  615,  615,  615,  615,  615,  615,  615,  615,
      615,  615,  615,  615,  615,  615,  615,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  616,  614,  616,  616,  616,

      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  615,
      615,  615,  615,  615,  615,  615,  615,  615,  615,  615,
      615,  615,  615,  615,  615,  615,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  615,  615,  615,
      615,  615,  615,  615,  615,  615,  615,  615,  615,  615,
      615,  615,  615,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  616,  616,  616,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  615,
      615,  615,  615,  615,  615,  615,  615,  615,  615,  615,
      615,  615,  615,  615,  614,  614,  614,  614,  614,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  614,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  616,  616,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  615,  615,  615,  615,
      615,  615,  615,  615,  615,  615,  615,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  616,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      614,  614,  614,  614,  614,  614,  615,  615,  615,  615,
      615,  614,  614,  614,  614,  614,  616,  616,  616,  616,
      616,  616,  614,  614,  614,  614,  615,  615,  614,  614,

      616,  616,  616,  614,  614,  614,  615,  614,  616,  616,
      614,  614,  614,    0,  614,  614
    } ;

static yyconst flex_int16_t yy_nxt[1028] =
    {   0,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   22,   35,   36,   37,   38,   39,   40,
       41,   42,   42,   43,   44,   45,   42,   46,   47,   48,
       49,   50,   42,   42,   51,   42,   42,   42,   42,   42,
       52,   53,   54,   55,   42,   56,   57,   58,   59,   60,
       61,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   61,   73,   61,   61,   74,   75,   76,
       77,   61,   61,   78,   79,   80,   61,   81,   82,   83,
       84,   85,   61,   61,   86,   61,   61,   61,   61,   61,
       87,   88,   89,   90,   61,   91,   92,   93,   94,   95,

       96,   96,   97,   98,   99,  100,  101,  102,  103,  104,
      105,  106,  107,   96,  108,   96,   96,  109,  110,  111,
      112,   96,   96,  113,  114,  115,   96,  116,  117,  118,
      119,  120,   96,   96,  121,   96,   96,   96,   96,   96,
      122,  123,  124,  125,   96,  126,  127,  128,  129,  130,
      131,  131,  132,  133,  134,  135,  136,  137,  138,  139,
      140,  141,  142,  131,  143,  131,  131,  144,  145,  146,
      147,  131,  131,  148,  149,  150,  131,  151,  152,  153,
      154,  155,  131,  131,  156,  131,  131,  131,  131,  131,
      157,  158,  159,  160,  131,  161,  162,  163,  164,  165,

      166,  166,  167,  168,  169,  170,  171,  172,  173,  174,
      175,  176,  177,  166,  178,  166,  166,  179,  180,  181,
      182,  166,  166,  183,  184,  185,  166,  186,  187,  188,
      189,  190,  166,  166,  191,  166,  166,  166,  166,  192,
      193,  194,  195,  196,  166,  197,  198,  199,  200,  201,
      202,  202,  203,  204,  205,  206,  207,  208,  209,  210,
      211,  212,  213,  202,  214,  202,  202,  215,  216,  217,
      218,  202,  202,  219,  220,  221,  202,  222,  223,  224,
      225,  226,  202,  202,  227,  202,  202,  202,  202,  202,
      228,  229,  230,  231,  202,  232,  233,  234,  235,  236,

       22,   22,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   22,  237,   22,   22,   38,   39,   40,
       41,   22,   22,  238,  239,  240,   22,  241,  242,  243,
      244,  245,   22,   22,  246,   22,   22,   22,   22,   22,
      247,  248,  249,  250,   22,  251,  252,   58,   59,   60,
      253,  253,  254,  255,  256,  257,  258,  259,  260,  261,
      262,  263,  264,  253,  265,  253,  253,  266,  267,  268,
      269,  253,  253,  270,  271,  272,  253,  273,  274,  275,
      276,  277,  253,  253,  278,  253,  253,  253,  253,  279,
      280,  281,  282,  283,  253,  284,  285,  286,  287,  288,

      289,  289,  290,  291,  292,  293,  294,  295,  296,  297,
      298,  299,  300,  289,  301,  289,  289,  302,  303,  304,
      305,  289,  289,  306,  307,  308,  289,  309,  310,  311,
      312,  313,  289,  289,  314,  289,  289,  289,  289,  315,
      316,  317,  318,  319,  289,  320,  321,  322,  323,  324,
      329,  331,  340,  332,  333,  330,  331,  346,  335,  336,
      334,  341,  349,  342,  359,  334,  360,  347,  334,  350,
      348,  364,  367,  334,  383,  388,  384,  412,  412,  368,
      391,  365,  364,  367,  366,  389,  613,  392,  390,  359,
      368,  360,  365,  400,  402,  366,  372,  401,  359,  364,

      360,  367,  405,  403,  359,  364,  360,  406,  368,  365,
      404,  364,  366,  367,  359,  365,  360,  364,  366,  367,
      368,  365,  367,  359,  366,  360,  368,  365,  407,  368,
      366,  359,  364,  360,  367,  408,  409,  413,  613,  332,
      333,  368,  365,  410,  428,  366,  334,  413,  612,  414,
      415,  479,  479,  416,  334,  416,  334,  468,  417,  417,
      331,  429,  335,  336,  334,  331,  444,  335,  336,  334,
      461,  609,  446,  606,  334,  417,  417,  334,  477,  478,
      417,  417,  334,  445,  611,  334,  413,  462,  414,  415,
      482,  483,  604,  334,  610,  334,  413,  609,  414,  415,

      497,  498,  608,  334,  607,  334,  513,  514,  413,  606,
      477,  478,  413,  334,  533,  534,  595,  334,  605,  535,
      536,  334,  604,  603,  602,  334,  334,  601,  413,  334,
      533,  534,  600,  413,  334,  533,  534,  334,  413,  599,
      535,  536,  334,  598,  597,  334,  596,  334,  595,  413,
      334,  575,  576,  594,  413,  334,  575,  576,  334,  413,
      593,  575,  576,  334,  592,  591,  334,  590,  334,  589,
      588,  334,  587,  586,  585,  584,  334,  375,  583,  375,
      582,  581,  580,  579,  578,  577,  574,  531,  530,  529,
      573,  572,  571,  570,  569,  568,  567,  566,  565,  564,

      563,  562,  561,  560,  559,  558,  557,  556,  555,  554,
      553,  552,  551,  550,  549,  548,  547,  546,  545,  544,
      543,  542,  541,  540,  539,  538,  537,  532,  475,  531,
      473,  530,  471,  529,  528,  527,  526,  525,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  512,  511,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  496,  495,  494,  493,  492,  491,  490,  489,
      488,  487,  486,  485,  484,  481,  480,  476,  475,  474,
      473,  472,  471,  470,  469,  467,  466,  465,  464,  463,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,

      450,  449,  448,  447,  446,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  411,
      325,  357,  374,  373,  372,  371,  370,  369,  363,  362,
      361,  339,  338,  337,  330,  328,  327,  326,  357,  374,
      373,  372,  371,  370,  369,  363,  362,  361,  339,  338,
      337,  330,  328,  327,  326,  374,  373,  372,  371,  370,
      369,  363,  362,  361,  330,  357,  374,  373,  372,  371,
      370,  369,  363,  362,  361,  339,  338,  337,  328,  327,
      326,  357,  374,  373,  372,  371,  370,  369,  363,  362,

      361,  339,  338,  337,  330,  328,  327,  326,  357,  374,
      373,  370,  369,  363,  362,  361,  339,  338,  337,  330,
      328,  327,  326,  399,  398,  397,  396,  395,  394,  393,
      387,  386,  385,  382,  381,  380,  379,  378,  377,  376,
      357,  374,  373,  372,  371,  370,  369,  363,  362,  361,
      339,  338,  337,  330,  358,  328,  327,  326,  357,  356,
      355,  354,  353,  352,  351,  345,  344,  343,  339,  338,
      337,  328,  327,  326,  325,  614,   21,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614
    } ;

static yyconst flex_int16_t yy_chk[1028] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       35,   36,  615,   36,   36,   35,   37,   50,   37,   37,
       36,   46,   51,   46,   81,   37,   81,   50,   36,   51,
       50,   85,   86,   37,  116,  120,  116,  331,  331,   86,
      121,   85,  155,  156,   85,  120,  613,  121,  120,  151,
      156,  151,  155,  159,  160,  155,  160,  159,  186,  190,

      186,  191,  214,  192,  222,  226,  222,  214,  191,  190,
      192,  245,  190,  227,  241,  226,  241,  277,  226,  246,
      227,  245,  278,  273,  245,  273,  246,  277,  279,  278,
      277,  309,  313,  309,  314,  279,  315,  332,  612,  332,
      332,  314,  313,  315,  352,  313,  332,  333,  611,  333,
      333,  413,  413,  334,  332,  334,  333,  401,  334,  334,
      335,  352,  335,  335,  333,  336,  370,  336,  336,  335,
      394,  609,  401,  606,  336,  416,  416,  335,  412,  412,
      417,  417,  336,  370,  605,  412,  414,  394,  414,  414,
      420,  420,  604,  412,  603,  414,  415,  601,  415,  415,

      436,  436,  600,  414,  598,  415,  453,  453,  477,  596,
      477,  477,  478,  415,  478,  478,  595,  477,  594,  479,
      479,  478,  593,  589,  588,  477,  479,  587,  533,  478,
      533,  533,  583,  534,  479,  534,  534,  533,  535,  582,
      535,  535,  534,  578,  577,  533,  574,  535,  573,  536,
      534,  536,  536,  572,  575,  535,  575,  575,  536,  576,
      571,  576,  576,  575,  569,  568,  536,  564,  576,  563,
      560,  575,  559,  557,  556,  552,  576,  616,  551,  616,
      548,  546,  545,  541,  540,  537,  532,  531,  530,  529,
      528,  527,  526,  525,  522,  521,  519,  518,  517,  515,

      514,  513,  512,  511,  510,  509,  506,  505,  503,  502,
      501,  499,  498,  497,  496,  495,  494,  491,  490,  488,
      487,  486,  484,  483,  482,  481,  480,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  465,  464,
      463,  462,  461,  460,  457,  456,  455,  454,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  440,  439,
      438,  437,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  424,  423,  422,  421,  419,  418,  411,  410,  409,
      408,  407,  404,  403,  402,  400,  398,  397,  396,  395,
      393,  392,  390,  389,  388,  387,  386,  385,  384,  383,

      377,  374,  373,  372,  371,  369,  368,  366,  365,  364,
      363,  362,  361,  360,  359,  356,  355,  354,  353,  351,
      350,  348,  347,  346,  345,  344,  343,  342,  341,  327,
      325,  323,  321,  320,  319,  318,  317,  316,  312,  311,
      310,  305,  304,  303,  301,  294,  292,  291,  287,  285,
      284,  283,  282,  281,  280,  276,  275,  274,  269,  268,
      267,  265,  258,  256,  255,  252,  251,  250,  249,  248,
      247,  244,  243,  242,  237,  235,  233,  232,  231,  230,
      229,  228,  225,  224,  223,  218,  217,  216,  207,  205,
      204,  200,  198,  197,  196,  195,  194,  193,  189,  188,

      187,  182,  181,  180,  178,  171,  169,  168,  164,  162,
      161,  158,  157,  154,  153,  152,  147,  146,  145,  143,
      136,  134,  133,  129,  127,  126,  125,  124,  123,  122,
      119,  118,  117,  112,  111,  110,  108,  101,   99,   98,
       94,   92,   91,   90,   89,   88,   87,   84,   83,   82,
       77,   76,   75,   73,   69,   66,   64,   63,   59,   57,
       56,   55,   54,   53,   52,   49,   48,   47,   41,   40,
       39,   28,   26,   25,   23,   21,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,

      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614,  614,  614,  614,
      614,  614,  614,  614,  614,  614,  614
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lextemplate.l"
#line 2 "lextemplate.l"
#define LIST                { strncat(buf, yytext, sizeof(buf) - strlen(buf) - 1); }
#define token(t)            { LIST; if (Opt_Token) printf("<%s>\n", #t); }
#define tokenString(t, s)   { LIST; if (Opt_Token) printf("<%s:%s>\n", t, s); }
#define MAX_LINE_LENGTH 257
#define MAX_ID_LENGTH 257
int Opt_Source = 1;
int Opt_Token = 1;
int Opt_Statistic = 1;
int linenum = 1;
char buf[MAX_LINE_LENGTH];

#line 892 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define COMMENT_ 2
#define PRAGMA 3
#define SOURCE 4
#define CHECK 5
#define STR 6
#define STR_END 7
#define TOKEN 8
#define STATISTIC 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 23 "lextemplate.l"

#line 1112 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 615 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 977 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "lextemplate.l"
{   tokenString("delim", "(");  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "lextemplate.l"
{   tokenString("delim", ")"); 	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "lextemplate.l"
{   tokenString("delim", ","); 	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "lextemplate.l"
{	tokenString("delim", ";"); 	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "lextemplate.l"
{   tokenString("delim", "[");  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "lextemplate.l"
{   tokenString("delim", "]");  }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "lextemplate.l"
{   tokenString("delim", "{");  }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "lextemplate.l"
{   tokenString("delim", "}");  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 33 "lextemplate.l"
{	token("+");	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 34 "lextemplate.l"
{	token("-");	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 "lextemplate.l"
{	token("*");	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "lextemplate.l"
{	token("/");	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 37 "lextemplate.l"
{	token("%");	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 38 "lextemplate.l"
{	token("=");	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 39 "lextemplate.l"
{	token("<");	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 40 "lextemplate.l"
{	token("<=");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 41 "lextemplate.l"
{	token("!=");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 42 "lextemplate.l"
{	token(">=");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 "lextemplate.l"
{	token(">");	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 44 "lextemplate.l"
{	token("==");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 45 "lextemplate.l"
{	token("&&");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 46 "lextemplate.l"
{	token("||");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 47 "lextemplate.l"
{	token("!");	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "lextemplate.l"
{	tokenString("KW", "while");	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "lextemplate.l"
{	tokenString("KW", "do");	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "lextemplate.l"
{	tokenString("KW", "if");	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "lextemplate.l"
{	tokenString("KW", "else");	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "lextemplate.l"
{	tokenString("KW", "true");	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "lextemplate.l"
{	tokenString("KW", "false");	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "lextemplate.l"
{	tokenString("KW", "for");	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "lextemplate.l"
{	tokenString("KW", "int");	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "lextemplate.l"
{	tokenString("KW", "print");	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "lextemplate.l"
{	tokenString("KW", "const");	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 60 "lextemplate.l"
{	tokenString("KW", "read");	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "lextemplate.l"
{	tokenString("KW", "boolean");	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "lextemplate.l"
{	tokenString("KW", "bool");	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 63 "lextemplate.l"
{	tokenString("KW", "void");	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 64 "lextemplate.l"
{	tokenString("KW", "float");	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 65 "lextemplate.l"
{	tokenString("KW", "double");	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 66 "lextemplate.l"
{	tokenString("KW", "string");	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 67 "lextemplate.l"
{tokenString("KW", "continue");	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 68 "lextemplate.l"
{	tokenString("KW", "break");		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 69 "lextemplate.l"
{	tokenString("KW", "return");	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 73 "lextemplate.l"
{	LIST; BEGIN PRAGMA;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 74 "lextemplate.l"
{ LIST;BEGIN SOURCE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 75 "lextemplate.l"
{ LIST;BEGIN TOKEN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 76 "lextemplate.l"
{ LIST;BEGIN STATISTIC;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 77 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
							exit(1);
						}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 80 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
							exit(1);
						}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "lextemplate.l"
{ LIST; Opt_Source=1;BEGIN CHECK;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "lextemplate.l"
{ LIST; Opt_Source=0;BEGIN CHECK;}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 86 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
							exit(1);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 88 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
							exit(1);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 "lextemplate.l"
{ LIST; Opt_Token=1;BEGIN CHECK;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 "lextemplate.l"
{ LIST; Opt_Token=0;BEGIN CHECK;}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 92 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
							exit(1);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 94 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
							exit(1);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "lextemplate.l"
{ LIST; Opt_Statistic=1;BEGIN CHECK;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "lextemplate.l"
{ LIST; Opt_Statistic=0;BEGIN CHECK;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 98 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
							exit(1);
						}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
							exit(1);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 111 "lextemplate.l"
{ LIST; BEGIN COMMENT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "lextemplate.l"
{ LIST; BEGIN COMMENT_;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 113 "lextemplate.l"
{	fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
				exit(1);
			}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 116 "lextemplate.l"
{ 	LIST;	
					if (Opt_Source)
					printf("%d:%s\n", linenum, buf);
						++linenum;
					buf[0] = '\0';
					BEGIN INITIAL;
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "lextemplate.l"
{ LIST; BEGIN COMMENT_;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 "lextemplate.l"
{ LIST; BEGIN COMMENT_;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 136 "lextemplate.l"
{ 	LIST;	
					if (Opt_Source)
					printf("%d:%s\n", linenum, buf);
						++linenum;
					buf[0] = '\0';
					BEGIN INITIAL;
				}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 146 "lextemplate.l"
{ LIST; BEGIN INITIAL;}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 148 "lextemplate.l"
{ 	LIST;	
					if (Opt_Source)
						printf("%d:%s\n", linenum, buf);
					++linenum;
					buf[0] = '\0';
					BEGIN COMMENT;
				}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 156 "lextemplate.l"
{ LIST; BEGIN COMMENT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 157 "lextemplate.l"
{ LIST; BEGIN COMMENT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 160 "lextemplate.l"
{ tokenString("uid", yytext);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 161 "lextemplate.l"
{ tokenString("integer", yytext);	}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 162 "lextemplate.l"
{ tokenString("float", yytext); 	}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 163 "lextemplate.l"
{ tokenString("scientific", yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 164 "lextemplate.l"
{ LIST;}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 167 "lextemplate.l"
{
    LIST;
    if (Opt_Source)
        printf("%d:%s\n", linenum, buf);
    ++linenum;
    buf[0] = '\0';
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 175 "lextemplate.l"
{ // Unrecognized character
    fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
    exit(1);
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 180 "lextemplate.l"
{ // Unrecognized character
    fprintf(stderr, "Error at line %d: %s\n", linenum, yytext);
    exit(1);
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 185 "lextemplate.l"
ECHO;
	YY_BREAK
#line 1625 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(COMMENT_):
case YY_STATE_EOF(PRAGMA):
case YY_STATE_EOF(SOURCE):
case YY_STATE_EOF(CHECK):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(STR_END):
case YY_STATE_EOF(TOKEN):
case YY_STATE_EOF(STATISTIC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 615 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 615 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 614);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 185 "lextemplate.l"



int main( int argc, char **argv )
{
    if (argc >= 2)
    {
        yyin = fopen( argv[1], "r" );
        if ( NULL == yyin ) {
            fprintf( stderr, "Cannot open: %s\n", argv[1] );
            exit(-1);
        }
    }
    else
    {
        yyin = stdin;
    }

    yylex();
	
	printf("%d:%s\n", linenum, buf);
	
    if (Opt_Statistic)
    {
        // Print frequency table
    }

    exit(0);
}

